Feature/323 install go tools
exasol/project-keeper pull request #362
Opened 2022-08-30 11:47 UTC by ckunki

Fixes #323

2022-08-30 14:01 UTC, kaklakariada requested changes
Code structure looks very good! Only some minor refactoring :)

2022-08-30 15:10 UTC, ckunki commented on project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoBinary.java
> +    public GoBinary install(final Path workingDirectory, final GoProcess goProcess) {
👍

2022-08-30 15:12 UTC, ckunki commented on project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoBinary.java
> +        return getGoBinPath().resolve("bin").resolve(nameWithSuffix());
not used for go binary itself

2022-08-31 08:44 UTC, kaklakariada requested changes

2022-08-31 08:44 UTC, kaklakariada commented on project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GoBinaryTest.java
> +    private final GoProcess goProcess = mock(GoProcess.class);
```suggestion
    @Mock
    private GoProcess goProcess;
```
Mock should be created automatically

2022-08-31 09:57 UTC, kaklakariada submitted a review, later dismissed

2022-08-31 11:42 UTC, kaklakariada approved these changes

2022-08-31 11:55 UTC, merged