Updated dependencies
exasol/project-keeper pull request #589
Opened 2024-10-15 14:25 UTC by ckunki

Closes #586
Closes #587
Closes #588

2024-10-15 15:32 UTC, ckunki commented
Error message 
> Component in org.apache.maven.plugins.annotations has been deprecated

See 
* https://maven.apache.org/ref/3.9.9/maven-core/apidocs/org/apache/maven/plugin/PluginParameterExpressionEvaluator.html
* https://stackoverflow.com/questions/6581828/what-is-the-replacement-for-mavenprojectbuilder-which-is-deprecated-in-maven-3
* https://maven.apache.org/maven-jsr330.html#how-to-use-jsr-330-in-plugins

2024-10-15 16:45 UTC, ckunki commented
Error message 
> Component in org.apache.maven.plugins.annotations has been deprecated

in [MavenProjectCrawlerMojo.java](https://github.com/exasol/project-keeper/blob/main/maven-project-crawler/src/main/java/com/exasol/projectkeeper/MavenProjectCrawlerMojo.java)

See 
* https://maven.apache.org/plugin-tools/maven-plugin-tools-annotations/index.html
* [PluginParameterExpressionEvaluator](https://maven.apache.org/ref/3.9.9/maven-core/apidocs/org/apache/maven/plugin/PluginParameterExpressionEvaluator.html)
* [stackoverflow 6581828](https://stackoverflow.com/questions/6581828/) -- what-is-the-replacement-for-mavenprojectbuilder-which-is-deprecated-in-maven-3
* https://maven.apache.org/maven-jsr330.html

2024-10-16 08:35 UTC, kaklakariada requested changes

2024-10-16 08:35 UTC, kaklakariada commented on doc/changes/changes_4.3.4.md
> +* #588: Fixed vulnerability CVE-2023-7272 in runtime dependency `org.glassfish:javax.json:1.1.4`
```suggestion
This release fixes vulnerability CVE-2024-47554 in transitive test dependency `commons-io:commons-io` via `com.exasol:maven-plugin-integration-testing:1.1.2` and `com.jcabi:jcabi-github:1.8.0`

The release ignores vulnerability CVE-2023-7272 in transitive runtime dependency `org.glassfish:javax.json:1.1.4` via `com.jcabi:jcabi-github:jar:1.9.1` as this is accepted for accessing exasol json documents on GitHub.

### Security

* #586: Fixed vulnerability CVE-2024-47554 in test dependency `commons-io:commons-io:2.11.0`
* #587: Fixed vulnerability CVE-2024-47554 in test dependency `commons-io:commons-io:2.13.0`
* #588: Ignore vulnerability CVE-2023-7272 in runtime dependency `org.glassfish:javax.json:1.1.4`
```

2024-10-16 08:35 UTC, kaklakariada commented on maven-project-crawler/pom.xml
> +                    </ignoredDependencies>
```suggestion
                    <ignoredDependencies>
                      <dependency>
                        <!-- provided -->
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-utils</artifactId>
                      </dependency>
                      <dependency>
                        <!-- provided -->
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-xml</artifactId>
                      </dependency>
                    </ignoredDependencies>
```

2024-10-16 08:35 UTC, kaklakariada commented on project-keeper-maven-plugin/pom.xml
> +                    </ignoredClassPatterns>
Replace this 
```suggestion
                    <ignoredDependencies>
                      <dependency>
                        <!-- provided -->
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-utils</artifactId>
                      </dependency>
                      <dependency>
                        <!-- provided -->
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-xml</artifactId>
                      </dependency>
                    </ignoredDependencies>
```

2024-10-16 10:48 UTC, kaklakariada approved these changes

2024-10-16 10:49 UTC, merged